// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
int A = (440);
int B = (494);
int C = (262);
int D = (294);
int E = (330);
int F = (349);
int G = (392);
int HA =(880);
int HB =(987);
int HC =(523);
int HD = (587);
int HE = (659);
int HF = (699);
int HG = (784);

int wholeNote = (3500);
int hn = wholeNote/2;
int qn = wholenote/4;
int DotHN = wholeNote * (3/4)+1;


Console.Beep (784);
Console.Beep(HG,DotHN );
Console.Beep(HE,wholeNote);
Console.Beep(HD,qn );
Console.Beep(HE,qn );
Console.Beep(HD,wholeNote);
Console.Beep(HC,qn) ;
Console.Beep(HD,qn) ;
Console.Beep(HC,qn) ;
Console.Beep(HE,qn);
Console.Beep(HC,hn);
Console.Beep(B, qn);
Console.Beep(HC,qn);
Console.Beep(B, DotHN);
//Console.Beep(1, qn);
Console.Beep(A, qn);
Console.Beep(B, qn);
Console.Beep(A, qn);
Console.Beep(HD,qn);
Console.Beep(A,qn);
Console.Beep(G, qn);
Console.Beep(A, qn);
Console.Beep(G, hn);
Console.Beep(F, qn);
Console.Beep(G, qn);
Console.Beep(F, DotHN);
Console.Beep(E, wholeNote);
Console.Beep(E, qn);
Console.Beep(F, qn);
Console.Beep(E,qn);
Console.Beep(A,qn);
Console.Beep(E,qn);
Console.Beep(D,qn);
Console.Beep(E,qn);
Console.Beep(D,hn);
Console.Beep(C,qn);
Console.Beep(D,qn);
Console.Beep(C,qn);